"""File output: song.ini generation and folder assembly."""
from __future__ import annotations
import os
import shutil
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class SongMetadata:
    name: str
    artist: str
    album: str = ""
    genre: str = "Rock"
    year: str = ""
    charter: str = "AutoChart"
    diff_guitar: int = -1
    preview_start_time: int = 0
    loading_phrase: str = "Chart generated by AutoChart"


def generate_song_ini(meta: SongMetadata, song_length_ms: int) -> str:
    """Generate a song.ini file content matching Clone Hero format."""
    lines = [
        "[song]",
        f"name = {meta.name}",
        f"artist = {meta.artist}",
        f"album = {meta.album}",
        f"genre = {meta.genre}",
        f"year = {meta.year}",
        f"charter = {meta.charter}",
        f"song_length = {song_length_ms}",
        f"diff_guitar = {meta.diff_guitar}",
        f"preview_start_time = {meta.preview_start_time}",
        f"loading_phrase = {meta.loading_phrase}",
    ]
    return "\n".join(lines)


def assemble_output_folder(
    output_dir: str,
    chart_content: str,
    ini_content: str,
    audio_source_path: str,
    album_art_path: Optional[str] = None,
) -> str:
    """Create a Clone Hero-readable folder with all required files.

    Returns the path to the created folder.
    """
    os.makedirs(output_dir, exist_ok=True)

    # Write notes.chart
    chart_path = os.path.join(output_dir, "notes.chart")
    with open(chart_path, "w", encoding="utf-8") as f:
        f.write(chart_content)

    # Write song.ini
    ini_path = os.path.join(output_dir, "song.ini")
    with open(ini_path, "w", encoding="utf-8") as f:
        f.write(ini_content)

    # Copy audio file (keep original format for now; conversion to ogg is separate)
    audio_ext = os.path.splitext(audio_source_path)[1]
    dest_audio = os.path.join(output_dir, f"song{audio_ext}")
    shutil.copy2(audio_source_path, dest_audio)

    # Copy album art if provided
    if album_art_path and os.path.isfile(album_art_path):
        art_ext = os.path.splitext(album_art_path)[1]
        dest_art = os.path.join(output_dir, f"album{art_ext}")
        shutil.copy2(album_art_path, dest_art)

    return output_dir
